services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: animal_coup
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      TZ: Asia/Bangkok
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d
      - /usr/share/zoneinfo/Asia/Bangkok:/etc/localtime
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      PMA_ARBITRARY: 0
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_data:


networks:
  app_network:
    driver: bridge
